version: '3.8'
services:

  orchestrator:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: coach
    volumes:
      - type: bind
        source: scripts
        target: /coach
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    stdin_open: true
    tty: true

  api:
    build: 
      context: ./api
      target: devcontainer
    volumes:
      - type: bind
        source: ./api
        target: /home/coach/api
    # ports:
    #   - "3000:3000"
    entrypoint: bash 
    stdin_open: true
    tty: true

  api-go: # Deprecated, to be removed.
    build: 
      context: ./api-go
      target: dev
    volumes:
      - type: bind
        source: ./api-go
        target: /coach
    ports:
      - "3000:3000"
    working_dir: /coach/cmd/server
    entrypoint: gin --appPort 8080 run .
    stdin_open: true
    tty: true

  database:
    container_name: coach-db-devcontainer 
