version: '3.8'
services:
  api:
    build: 
      context: .
      target: dev 
    env_file:
      .env
    ports:
      - "8080:8080"
    container_name: aisu-api
  database:
    image: mongo:5.0
    container_name: aisu-db
    ports:
    - "27017:27017"
