version: '3.8'
services:
  api:
    build: 
      context: ./api
      target: test
    env_file:
      ./api/.env
    ports:
      - "8080:8080"
    container_name: coach-api
  database:
    image: mongo:5.0
    container_name: coach-db
    ports:
    - "27017:27017"

