FROM node:21.6.1 as base

WORKDIR /ui

COPY package.json .
COPY package-lock.json .

RUN npm install --omit=dev

CMD ["/usr/bin/env", "bash"]


FROM base as devcontainer

RUN npm install --dev

ENTRYPOINT ["/usr/bin/env", "bash"]


FROM base as dev 

COPY . /ui

ENTRYPOINT ["npm", "run", "dev"]
