# Stage 1: Base Image
FROM python:3.12.4 as core

# Update package list and install any required packages
RUN apt update && apt install -y \
    # Add packages here if needed, e.g., \
    # build-essential \
    && rm -rf /var/lib/apt/lists/*

# Create a group and user for the application
RUN groupadd -r applications && useradd -r -g applications coach

# Create the home directory and set ownership
RUN mkdir -p /home/coach && chown coach:applications /home/coach

# Switch to the 'coach' user
USER coach 

# Set working directory and environment variable
WORKDIR /home/coach/api
ENV PYTHONPATH=/home/coach/api

# Stage 2: Development Container
FROM core as devcontainer

# Install pipenv
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile* ./

# Install dependencies including development dependencies
RUN python -m pipenv install --dev

# Set the entrypoint for development
ENTRYPOINT ["bash"]

# Stage 3: Testing
FROM core as test

# Set working directory
WORKDIR /home/coach

# Copy application files
COPY . .

# Install dependencies from requirements.txt
RUN pip install -r requirements.txt

# Set the default command for testing
CMD ["python", "-m", "coach"]
